export const TODOLOADING = "TODOLOADING";
export const TODOERROR = "TODOERROR";
export const TODOSUCCESS = "TODOSUCCESS";

export const POSTTODOLOADING = "POSTTODOLOADING";
export const POSTTODOERROR = "POSTTODOERROR";
export const POSTTODOSUCCESS = "POSTTODOSUCCESS";

export const PATCHTODOLOADING = "PATCHTODOLOADING";
export const PATCHTODOERROR = "PATCHTODOERROR";
export const PATCHTODOSUCCESS = "PATCHTODOSUCCESS";
