export const USERLOGINLOADING = "USERLOGINLOADING";
export const USERLOGINERROR = "USERLOGINERROR";
export const USERLOGINSUCCESS = "USERLOGINSUCCESS";

export const USERSIGNUPLOADING = "USERSIGNUPLOADING";
export const USERSIGNUPERROR = "USERSIGNUPERROR";
export const USERSIGNUPSUCCESS = "USERSIGNUPSUCCESS";
